import React, { useEffect, useState } from "react";
import { invokeBackend } from "../../lib/api/errors";
import { logToBackend } from "../../lib/diagnostics";
import { getString } from "../../lib/i18n/index";
import type { CaptionTrack } from "../../types/video";
import { usePlayerStore } from "../../store/usePlayerStore";

const FETCH_MAX_ATTEMPTS = 3;
const FETCH_RETRY_MS = 1500;
const FETCH_FAILED_NOTICE_MS = 5000;

export type CaptionCue = {
  start: number;
  end: number;
  text: string;
};

interface SubtitleOverlayProps {
  captions: CaptionTrack[];
  selectedCaptionId: string;
  currentTime?: number;
  shouldShowControls: boolean;
}

function trimPunctuation(word: string): string {
  return word.replace(/^[^a-zA-Z0-9]+|[^a-zA-Z0-9]+$/g, "");
}

function equalsWords(words1: string[], words2: string[]): boolean {
  if (words1.length !== words2.length) return false;
  for (let i = 0; i < words1.length; i++) {
    const w1 = words1[i];
    const w2 = words2[i];
    if (w1 === undefined || w2 === undefined) return false;
    const w1Clean = trimPunctuation(w1).toLowerCase();
    const w2Clean = trimPunctuation(w2).toLowerCase();
    if (w1Clean !== w2Clean) {
      return false;
    }
  }
  return true;
}

function longestSuffixPrefixOverlap(previous: string[], latest: string[]): number {
  const maxOverlap = Math.min(previous.length, latest.length);
  for (let count = maxOverlap; count >= 1; count--) {
    const previousSuffix = previous.slice(-count);
    const latestPrefix = latest.slice(0, count);
    if (equalsWords(previousSuffix, latestPrefix)) {
      return count;
    }
  }
  return 0;
}

function splitWords(line: string): string[] {
  return line.split(/\s+/).filter(Boolean);
}

function latestRollingCaptionLine(lines: string[]): string {
  const line0 = lines[0];
  if (lines.length === 1 && line0 !== undefined) return line0;

  const latestLine = lines[lines.length - 1];
  const previousLine = lines[lines.length - 2];
  if (latestLine === undefined || previousLine === undefined) return "";

  const previousWords = splitWords(previousLine);
  const latestWords = splitWords(latestLine);

  if (previousWords.length === 0 || latestWords.length === 0) return latestLine;

  const overlap = longestSuffixPrefixOverlap(previousWords, latestWords);
  const freshWords = latestWords.slice(overlap);

  if (freshWords.length > 0) {
    return freshWords.join(" ");
  }
  return latestLine;
}

export function cleanCueText(text: string, isAutoGenerated: boolean): string {
  const normalized = text
    .replace(/\u00A0/g, " ")
    .replace(/[ \t\v\f\r]+/g, " ");

  const lines = normalized
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) return "";

  if (isAutoGenerated) {
    return latestRollingCaptionLine(lines);
  }

  return lines.slice(-2).join("\n").trim();
}

function parseVttTimestamp(value: string) {
  const parts = value.trim().split(":");
  const secondsPart = parts.pop() || "0";
  const seconds = Number(secondsPart.replace(",", "."));
  const minutes = Number(parts.pop() || 0);
  const hours = Number(parts.pop() || 0);
  return hours * 3600 + minutes * 60 + seconds;
}

function parseVttCues(vtt: string, isAutoGenerated: boolean): CaptionCue[] {
  return vtt
    .replace(/\r/g, "")
    .split("\n\n")
    .flatMap((block) => {
      const lines = block.split("\n").filter(Boolean);
      const timingIndex = lines.findIndex((line) => line.includes("-->"));
      if (timingIndex < 0) return [];

      const timingLine = lines[timingIndex];
      if (!timingLine) return [];
      const [startRaw, endRaw] = timingLine.split("-->");
      if (!startRaw || !endRaw) return [];

      const end = endRaw.trim().split(/\s+/)[0];
      if (!end) return [];
      const text = lines
        .slice(timingIndex + 1)
        .join("\n")
        .replace(/<[^>]*>/g, "")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .trim();

      if (!text) return [];
      const cleanedText = cleanCueText(text, isAutoGenerated);
      if (!cleanedText) return [];

      return [
        {
          start: parseVttTimestamp(startRaw),
          end: parseVttTimestamp(end),
          text: cleanedText,
        },
      ];
    });
}

function parseTimedTextCues(text: string, isAutoGenerated: boolean): CaptionCue[] {
  const doc = new DOMParser().parseFromString(text, "text/xml");
  return Array.from(doc.querySelectorAll("text")).flatMap((node) => {
    const start = Number(node.getAttribute("start"));
    const duration = Number(node.getAttribute("dur") || 0);
    const content = (node.textContent || "").trim();
    if (!Number.isFinite(start) || !content) return [];
    
    const cleanedText = cleanCueText(content, isAutoGenerated);
    if (!cleanedText) return [];

    return [{ start, end: start + duration, text: cleanedText }];
  });
}

function parseJsonCues(jsonText: string, isAutoGenerated: boolean): CaptionCue[] {
  try {
    const data = JSON.parse(jsonText);
    if (data && Array.isArray(data.events)) {
      return data.events.flatMap((event: any) => {
        const start = (event.tStartMs || 0) / 1000;
        const duration = (event.dDurationMs || 0) / 1000;
        const text = (event.segs || [])
          .map((seg: any) => seg.utf8 || "")
          .join("")
          .trim();
        if (!text) return [];

        const cleanedText = cleanCueText(text, isAutoGenerated);
        if (!cleanedText) return [];

        return [{ start, end: start + duration, text: cleanedText }];
      });
    }
  } catch (error) {
    void logToBackend("warn", "subtitle JSON parse failed", { cause: String(error) });
  }
  return [];
}

export function parseCaptionCues(text: string, isAutoGenerated: boolean): CaptionCue[] {
  const trimmed = text.trim();
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    return parseJsonCues(trimmed, isAutoGenerated);
  }
  if (trimmed.startsWith("WEBVTT") || trimmed.includes("-->")) {
    return parseVttCues(trimmed, isAutoGenerated);
  }
  return parseTimedTextCues(trimmed, isAutoGenerated);
}

// Optimized binary search active cue finder - O(log N)
function findActiveCue(cues: CaptionCue[], time: number): CaptionCue | null {
  if (cues.length === 0) return null;

  let low = 0;
  let high = cues.length - 1;
  let bestIdx = -1;

  while (low <= high) {
    const mid = (low + high) >> 1;
    const midCue = cues[mid];
    if (midCue !== undefined && midCue.start <= time) {
      bestIdx = mid;
      low = mid + 1;
    } else {
      high = mid - 1;
    }
  }

  if (bestIdx !== -1) {
    const cue = cues[bestIdx];
    if (cue !== undefined) {
      if (time >= cue.start && time <= cue.end) {
        return cue;
      }
      for (let i = bestIdx - 1; i >= 0; i--) {
        const c = cues[i];
        if (c === undefined) continue;
        if (time - c.start >= 5) break;
        if (time >= c.start && time <= c.end) {
          return c;
        }
      }
    }
  }
  return null;
}

export const SubtitleOverlay: React.FC<SubtitleOverlayProps> = ({
  captions,
  selectedCaptionId,
  currentTime,
  shouldShowControls,
}) => {
  const playbackTime = usePlayerStore((state) => currentTime ?? (selectedCaptionId === "off" ? 0 : state.currentTime));
  const [captionCues, setCaptionCues] = useState<CaptionCue[]>([]);
  const [trackFailed, setTrackFailed] = useState(false);
  
  const subtitleStyle = usePlayerStore((s) => s.subtitleStyle);

  useEffect(() => {
    const caption = captions.find((item) => item.id === selectedCaptionId);
    if (!caption) {
      setCaptionCues([]);
      setTrackFailed(false);
      return;
    }

    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | null = null;
    let attempt = 0;

    const load = () => {
      invokeBackend<string>("fetch_subtitles", { url: caption.url })
        .then((text) => {
          if (cancelled) return;
          setCaptionCues(parseCaptionCues(text, !!caption.isAutoGenerated));
          setTrackFailed(false);
        })
        .catch((error) => {
          if (cancelled) return;
          attempt += 1;
          setCaptionCues([]);
          void logToBackend("warn", "subtitle track fetch failed", {
            label: caption.label,
            languageCode: caption.languageCode,
            autoGenerated: !!caption.isAutoGenerated,
            attempt,
            cause: String(error),
          });
          // Auto-translated tracks are the ones YouTube rate-limits, and it
          // clears within seconds — so a couple of retries recovers a track that
          // would otherwise stay silently blank for the whole video.
          if (attempt >= FETCH_MAX_ATTEMPTS) {
            setTrackFailed(true);
            return;
          }
          timer = setTimeout(load, FETCH_RETRY_MS * attempt);
        });
    };

    load();

    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [captions, selectedCaptionId]);

  useEffect(() => {
    if (!trackFailed) return;
    const timer = setTimeout(() => setTrackFailed(false), FETCH_FAILED_NOTICE_MS);
    return () => clearTimeout(timer);
  }, [trackFailed]);

  const activeCue =
    selectedCaptionId === "off"
      ? null
      : findActiveCue(captionCues, playbackTime);


  if (!activeCue && !trackFailed) return null;

  const hexColor = (subtitleStyle.backgroundColor || "#000000").replace("#", "");
  const r = parseInt(hexColor.substring(0, 2), 16) || 0;
  const g = parseInt(hexColor.substring(2, 4), 16) || 0;
  const b = parseInt(hexColor.substring(4, 6), 16) || 0;
  const bgRgba = `rgba(${r}, ${g}, ${b}, ${subtitleStyle.backgroundOpacity})`;

  const textStyle: React.CSSProperties = {
    fontSize: `${subtitleStyle.fontSize}px`,
    color: subtitleStyle.textColor,
    fontWeight: subtitleStyle.isBold ? "700" : "500",
  };

  const containerStyle: React.CSSProperties = {
    backgroundColor: bgRgba,
    padding: "6px 16px",
    borderRadius: "8px",
    boxShadow: "0 20px 40px -10px color-mix(in srgb, var(--color-chrome-black) 50%, transparent)",
    lineHeight: "1.35",
    ...textStyle,
  };

  const bottomVal = shouldShowControls
    ? subtitleStyle.bottomPadding + 64
    : subtitleStyle.bottomPadding;

  return (
    <div
      className="pointer-events-none absolute inset-x-4 z-30 flex justify-center px-4 text-center transition-[bottom] duration-150"
      style={{ bottom: `${bottomVal}px` }}
    >
      <span style={containerStyle}>
        {activeCue ? activeCue.text : getString("subtitles_track_unavailable")}
      </span>
    </div>
  );
};

export default SubtitleOverlay;
